### PR TITLE
fix: parsing regexes coverted to raw strings

### PR DESCRIPTION
**Pull request by casperstorm**
## Proposed Changes
  - Changes relevant regexes to raw regexes (Thanks @Bananaman)

Note: this needs to be proper tested.

## Checklist

- [ ] Tested on Windows
- [x] Tested on MacOS
- [ ] Tested on Linux
- [x] Added an entry to `CHANGELOG.md` if knowledge of this change could be valuable to users

### CODE REVIEW

**Comment by casperstorm** [comment]
@Bananaman Should we change these as well?

https://github.com/ajour/ajour/blob/924386eb67d52e45092d1d0d52ebb27fe01085ab/crates/core/src/parse.rs#L1015-L1016

https://github.com/ajour/ajour/blob/924386eb67d52e45092d1d0d52ebb27fe01085ab/crates/core/src/parse.rs#L1024-L1025

**Comment by Bananaman** [comment]
Yeah, let's make every regex raw to clean things up. :)

**Comment by Bananaman** [comment]
@casperstorm +1. After carefully reading through every change, it all looks correct. Functionality of every regex is the same before and after, but it's a lot cleaner and easier to edit now.

If it all passes through testing/usage (which it should), it's good to go now!

**Comment by casperstorm** [comment]
@Bananaman Great, thanks again.
@tarkah if you have time, could you test this PR and see if you have any troubles with install/matching addons?

**Pull request merged**
