### PR TITLE
feat: context localizations

### PR DESCRIPTION
**Pull request by casperstorm**
## Proposed Changes
  - Quite a few error has not yet been localized.

## Checklist

- [ ] Tested on Windows
- [ ] Tested on MacOS
- [ ] Tested on Linux
- [ ] Added an entry to `CHANGELOG.md` if knowledge of this change could be valuable to users

### CODE REVIEW

**Comment by casperstorm** [comment]
@tarkah Would you be able to look at getting a generic "IO error" for the `error-update-ajour` as we talked about on Discord? Im a little unsure how to do it with the context and AnyHow 🤔 I am thinking we can have a `error-io-update-ajour` for it, or just use the other if we only want one?

**Comment by tarkah** [comment]
Sounds good! I'll at least add the code to match the downcasted error on IO error and log things so we can test what actually happens when we try to self update from a folder we don't have permissions to. Then you can play around with an error message for it.

**Comment by tarkah** [comment]
@casperstorm Check out my latest commit, it should make sense how I'm downcasting to get to check for io error / permissions issue. I've not added the "key" for localization yet, figured you could mess with that.

Note I modified the version so we could test the self update feature and I tested by copying to my C:\ root and was able to get the custom context for permissions issue! Make sure to revert version before merging.

**Comment by casperstorm** [comment]
Make sense, and works perfectly!

**Pull request merged**
